name: general
folder: data/synthetic
camera_data: camera_general.csv
trajectory_data: traj_general.csv


total_traj_num: 500
p0: [0.5, -2.4, 0.4] # m
dp0: [0.1, 0.1, 0.1]
v0:  [0.0, 3.0, 1.5] # m/s
dv0: [0.5, 1.0, 1.0] 
w0: [10.0, 0.0, 0.0] # hz
dw0: [10, 30, 10]
uv_noise: 3 # px
t_max: 1.0 # sec
seq_len: 200
z0: -999.9 # bounce of table
batch_size: 16