name: nonoise_nospin_nobounce
folder: data/synthetic
camera_data: camera_nonoise_nospin_nobounce.csv
trajectory_data: traj_nonoise_nospin_nobounce.csv

batch_size: 32
z0: -100.0 # bounce of table
total_traj_num: 500
p0: [0.5, -2.4, 0.4] # m
dp0: [0.1, 0.1, 0.1]
v0:  [0.0, 3.0, 1.5] # m/s
dv0: [0.5, 1.0, 1.0] 
w0: [0.0, 0.0, 0.0] # hz
dw0: [0.01, 0.01, 0.01] 
uv_noise: 0.1 # px
t_max: 1.0 # sec
seq_len: 200
