defaults:
  - model: physics
  - dataset: synthetic/nonoise_consspin_nobounce
  - _self_

task:
  generate_data: False
  train: True

camera:
  folder: conf/camera
  cam_ids:
    - '22276213'
    - '22276209'
    - '22276216'


  


  
