defaults:
  - model: traj/phybounce
  - estimator: gt
  - dataset: synthetic/general
  - _self_

hydra:
  output_subdir: null
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

task:
  generate_data: true
  train: True

camera:
  folder: conf/camera
  cam_ids:
    - '22276213'
    - '22276209'
    - '22276216'


  


  
