defaults:
  - model: traj/mlayer
  - estimator: optim_layer
  - dataset: synthetic/nonoise_consspin_nobounce
  - _self_

hydra:
  output_subdir: null
  run:
    dir: null

task:
  generate_data: False
  train: True

camera:
  folder: conf/camera
  cam_ids:
    - '22276213'
    - '22276209'
    - '22276216'


  


  
