defaults:
  - model: traj/mnn
  - estimator: optim_layer
  - dataset: real/tennis
  - _self_

hydra:
  output_subdir: null
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

task:
  generate_data: False
  train: True




  


  
